# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pawel/Documents/Projekty/Metal/MetalApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pawel/Documents/Projekty/Metal/MetalApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pawel/Documents/Projekty/Metal/MetalApp/CMakeFiles /Users/pawel/Documents/Projekty/Metal/MetalApp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pawel/Documents/Projekty/Metal/MetalApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyApp

# Build rule for target.
MyApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyApp
.PHONY : MyApp

# fast build rule for target.
MyApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/build
.PHONY : MyApp/fast

#=============================================================================
# Target rules for targets named METAL_CPP

# Build rule for target.
METAL_CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 METAL_CPP
.PHONY : METAL_CPP

# fast build rule for target.
METAL_CPP/fast:
	$(MAKE) $(MAKESILENT) -f metal-cmake/CMakeFiles/METAL_CPP.dir/build.make metal-cmake/CMakeFiles/METAL_CPP.dir/build
.PHONY : METAL_CPP/fast

Src/MyAppDelegate.o: Src/MyAppDelegate.m.o
.PHONY : Src/MyAppDelegate.o

# target to build an object file
Src/MyAppDelegate.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/MyAppDelegate.m.o
.PHONY : Src/MyAppDelegate.m.o

Src/MyMTKViewDelegate.o: Src/MyMTKViewDelegate.cpp.o
.PHONY : Src/MyMTKViewDelegate.o

# target to build an object file
Src/MyMTKViewDelegate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/MyMTKViewDelegate.cpp.o
.PHONY : Src/MyMTKViewDelegate.cpp.o

Src/MyMTKViewDelegate.i: Src/MyMTKViewDelegate.cpp.i
.PHONY : Src/MyMTKViewDelegate.i

# target to preprocess a source file
Src/MyMTKViewDelegate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/MyMTKViewDelegate.cpp.i
.PHONY : Src/MyMTKViewDelegate.cpp.i

Src/MyMTKViewDelegate.s: Src/MyMTKViewDelegate.cpp.s
.PHONY : Src/MyMTKViewDelegate.s

# target to generate assembly for a file
Src/MyMTKViewDelegate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/MyMTKViewDelegate.cpp.s
.PHONY : Src/MyMTKViewDelegate.cpp.s

Src/Renderer.o: Src/Renderer.cpp.o
.PHONY : Src/Renderer.o

# target to build an object file
Src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/Renderer.cpp.o
.PHONY : Src/Renderer.cpp.o

Src/Renderer.i: Src/Renderer.cpp.i
.PHONY : Src/Renderer.i

# target to preprocess a source file
Src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/Renderer.cpp.i
.PHONY : Src/Renderer.cpp.i

Src/Renderer.s: Src/Renderer.cpp.s
.PHONY : Src/Renderer.s

# target to generate assembly for a file
Src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/Renderer.cpp.s
.PHONY : Src/Renderer.cpp.s

Src/main.o: Src/main.cpp.o
.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... METAL_CPP"
	@echo "... MyApp"
	@echo "... Src/MyAppDelegate.o"
	@echo "... Src/MyMTKViewDelegate.o"
	@echo "... Src/MyMTKViewDelegate.i"
	@echo "... Src/MyMTKViewDelegate.s"
	@echo "... Src/Renderer.o"
	@echo "... Src/Renderer.i"
	@echo "... Src/Renderer.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

